#!/usr/bin/env python3
"""Prepare a Webots-friendly URDF and optionally convert it to PROTO."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROS_MESH_PREFIX = "package://dofbot_description/meshes/"


def rewrite_urdf_for_webots(input_urdf: Path, output_urdf: Path, mesh_dir: Path) -> None:
    text = input_urdf.read_text(encoding="utf-8")
    mesh_prefix_text = os.path.relpath(mesh_dir.resolve(), output_urdf.parent.resolve()).replace("\\", "/")
    mesh_prefix_text = mesh_prefix_text.rstrip("/") + "/"
    updated = text.replace(ROS_MESH_PREFIX, mesh_prefix_text)
    output_urdf.parent.mkdir(parents=True, exist_ok=True)
    output_urdf.write_text(updated, encoding="utf-8")


def run_converter(sim_urdf: Path, output_proto: Path, box_collision: bool) -> None:
    cmd = [
        sys.executable,
        "-m",
        "urdf2webots.importer",
        f"--input={sim_urdf}",
        f"--output={output_proto}",
    ]
    if box_collision:
        cmd.append("--box-collision")
    subprocess.run(cmd, check=True)


def patch_proto_fixed_base(output_proto: Path) -> None:
    text = output_proto.read_text(encoding="utf-8")
    pattern = (
        r"\n\s+name IS name\n"
        r"\s+boundingObject USE base_link\n"
        r"\s+physics Physics \{\n"
        r"\s+\}\n"
    )
    replacement = "\n    name IS name\n    # Fixed base for manipulator stability.\n"
    updated, count = re.subn(pattern, replacement, text)
    if count == 0:
        return
    output_proto.write_text(updated, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-urdf",
        default="description/urdf/dofbot.urdf",
        help="Source URDF path (ROS-style mesh package URIs supported).",
    )
    parser.add_argument(
        "--output-urdf",
        default="simulation/webots/dofbot.sim.urdf",
        help="Output URDF path with Webots-compatible mesh paths.",
    )
    parser.add_argument(
        "--output-proto",
        default="simulation/webots/protos/Dofbot.proto",
        help="Output PROTO path generated by urdf2webots.",
    )
    parser.add_argument(
        "--skip-convert",
        action="store_true",
        help="Only rewrite URDF; do not invoke urdf2webots.",
    )
    parser.add_argument(
        "--mesh-dir",
        default="description/meshes",
        help="Mesh directory referenced by package://dofbot_description/meshes/",
    )
    parser.add_argument(
        "--box-collision",
        action="store_true",
        default=True,
        help="Use simple collision boxes when converting to PROTO (default: enabled).",
    )
    parser.add_argument(
        "--no-box-collision",
        action="store_false",
        dest="box_collision",
        help="Disable simple box collision approximation.",
    )
    parser.add_argument(
        "--fixed-base",
        action="store_true",
        default=True,
        help="Patch generated PROTO to keep robot base fixed (default: enabled).",
    )
    parser.add_argument(
        "--no-fixed-base",
        action="store_false",
        dest="fixed_base",
        help="Do not patch generated PROTO base physics.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_urdf = Path(args.input_urdf)
    output_urdf = Path(args.output_urdf)
    output_proto = Path(args.output_proto)
    mesh_dir = Path(args.mesh_dir)

    if not input_urdf.exists():
        print(f"Input URDF not found: {input_urdf}", file=sys.stderr)
        return 2

    if not mesh_dir.exists():
        print(f"Mesh directory not found: {mesh_dir}", file=sys.stderr)
        return 2

    rewrite_urdf_for_webots(input_urdf, output_urdf, mesh_dir)
    print(f"Wrote rewritten URDF: {output_urdf}")

    if args.skip_convert:
        return 0

    try:
        run_converter(output_urdf, output_proto, args.box_collision)
    except subprocess.CalledProcessError as exc:
        print("urdf2webots conversion failed.", file=sys.stderr)
        print(f"Command: {' '.join(exc.cmd)}", file=sys.stderr)
        return exc.returncode or 1
    except Exception as exc:  # pragma: no cover - defensive path
        print(f"Failed to run urdf2webots: {exc}", file=sys.stderr)
        return 1

    if args.fixed_base:
        patch_proto_fixed_base(output_proto)
    print(f"Wrote Webots PROTO: {output_proto}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
